sudo: required
services:
  - docker

before_install:
  - docker build -t my-image -f Dockerfile.dev .

scripts:
  - docker run my-image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react-sample'
  env: 'Dockerreactsample-env'
  bucket_name: 'elasticbeanstalk-us-east-2-347520882069'
  buccet_path: 'docker-react-sample'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
